project:
  type: book

book:
  title: "Wild recipes"
  author: "Mike Page"
  date: "22/01/2024"
  cover-image: cover.png
  chapters:
    - index.qmd
    - structure.qmd

    - part: ggplot2
      chapters:
      - ggplot2-annotations-sizes.qmd
      - gglot2-annotations-positions.qmd
      # wrapping annotations in a list
      # scanning plot objects for information
      
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



